/**
This file was automatically generated by oxygine-editor. Don't change it!
*/
#pragma once

#include "Sprite.h"
#include "ActorsFactory.h"
using namespace oxygine;

DECLARENS_SMART(oxygine, Sprite, spSprite);
DECLARE_SMART(playground, spplayground);
//
class playground: public ActorX
{
public:
    FACTORY_ACTOR(playground, "playground");

    spSprite field;
    spSprite pieces;
    
};

